{{- if .Values.gateway.enabled }}
{{- range .Values.gateway.routes }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "uap.commonLabels" $ | nindent 4 }}
spec:
  parentRefs:
    - name: {{ $.Values.gateway.name }}
  hostnames:
    - {{ tpl .hostname $ | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .path | default "/" }}
      backendRefs:
        - name: {{ .service }}
          port: {{ .port }}
---
{{- end }}
{{- end }}
