apiVersion: v1
kind: Secret
metadata:
  name: uap-platform-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "uap.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  platform-database-url: {{ .Values.secrets.platformDatabaseURL | quote }}
  redis-url: {{ .Values.secrets.redisURL | quote }}
  clickhouse-dsn: {{ .Values.secrets.clickhouseDsn | quote }}
  temporal-address: {{ .Values.secrets.temporalAddress | quote }}
  postgres-user: {{ .Values.secrets.postgresUser | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  postgres-database: {{ .Values.secrets.postgresDatabase | quote }}
  keycloak-admin-user: {{ .Values.secrets.keycloakAdminUser | quote }}
  keycloak-admin-password: {{ .Values.secrets.keycloakAdminPassword | quote }}
  grafana-admin-user: {{ .Values.secrets.grafanaAdminUser | quote }}
  grafana-admin-password: {{ .Values.secrets.grafanaAdminPassword | quote }}
  minio-root-user: {{ .Values.secrets.minioRootUser | quote }}
  minio-root-password: {{ .Values.secrets.minioRootPassword | quote }}
  livekit-api-key: {{ .Values.secrets.livekitApiKey | quote }}
  livekit-api-secret: {{ .Values.secrets.livekitApiSecret | quote }}

