{{- range $name, $cfg := .Values.deployments }}
{{- if ne (default true $cfg.enabled) false }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uap.serviceAccountName" (dict "name" $name) }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "uap.workloadLabels" (dict "root" $ "name" $name "mesh" ($cfg.mesh | default false)) | nindent 4 }}
---
{{- end }}
{{- end }}
{{- range $name, $cfg := .Values.statefulWorkloads }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uap.serviceAccountName" (dict "name" $name) }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "uap.workloadLabels" (dict "root" $ "name" $name "mesh" false) | nindent 4 }}
---
{{- end }}

